export { BadgeSize } from './badge-size.enum';
export { ButtonType } from './button-type-enum';
export { CandidateTab } from './candidate-tab.enum';
export { Color } from './colors.enum';
export { IconName } from './icon-name.enum';
export { IconSize } from './icon-size.enum';
export { LoaderSize } from './loader-size.enum';
export { PhotoType } from './photo-type.enum';
export { ProfileTab } from './profile-tab.enum';
