parserOptions:
    project:
        - ./tsconfig.json

extends:
    - ../.eslintrc.yml
    - plugin:react-hooks/recommended

settings:
    import/ignore:
        - 'react-native'

rules:
    import/extensions: off
