const EmployerOnboardingFormValidationRule = {
    MIN_FULL_NAME_LENGTH: 3,
    MAX_FULL_NAME_LENGTH: 50,
    MIN_LINKEDIN_LINK_LENGTH: 30,
    MAX_LINKEDIN_LINK_LENGTH: 250,
    MIN_COMPANY_WEBSITE_LINK_LENGTH: 5,
    MAX_COMPANY_WEBSITE_LINK_LENGTH: 50,
    MIN_COMPANY_NAME_LENGTH: 2,
    MAX_COMPANY_NAME_LENGTH: 50,
    MIN_POSITION_LENGTH: 2,
    MAX_POSITION_LENGTH: 50,
    MAX_DESCRIPTION_LENGTH: 250,
} as const;

export { EmployerOnboardingFormValidationRule };
