const FONTS = {
    h1: {
        fontFamily: 'Inter',
        fontWeight: 700,
        fontSize: 42,
        lineHeight: 50.83,
        color: '#222',
    },
    h2: {
        fontFamily: 'Inter',
        fontWeight: 700,
        fontSize: 28,
        lineHeight: 36.4,
        color: '#222',
    },
    h3: {
        fontFamily: 'Inter',
        fontWeight: 500,
        fontSize: 26,
        lineHeight: 34,
        color: '#222',
    },
    h4: {
        fontFamily: 'Inter',
        fontWeight: 500,
        fontSize: 24,
        lineHeight: 32.29,
        color: '#222',
    },
    h5: {
        fontFamily: 'Inter',
        fontWeight: 500,
        fontSize: 18,
        lineHeight: 25.56,
        color: '#222',
    },
    h6: {
        fontFamily: 'Inter',
        fontWeight: 400,
        fontSize: 16,
        lineHeight: 22.48,
        color: '#222',
    },
    menu: {
        fontFamily: 'Inter',
        fontWeight: 400,
        fontSize: 18,
        lineHeight: 21.78,
        color: '#222',
    },
    body1: {
        fontFamily: 'Inter',
        fontWeight: 400,
        fontSize: 14,
        lineHeight: 16.94,
        color: '#222',
    },
    tub: {
        fontFamily: 'Inter',
        fontWeight: 400,
        fontSize: 16,
        lineHeight: 18.75,
        color: '#222',
    },
    button: {
        fontFamily: 'Inter',
        fontWeight: 400,
        fontSize: 16,
        lineHeight: 18.75,
        color: '#222',
    },
    caption: {
        fontFamily: 'Inter',
        fontWeight: 400,
        fontSize: 12,
        lineHeight: 14.52,
        color: '#222',
    },
    input: {
        fontFamily: 'Inter',
        fontWeight: 400,
        fontSize: 13,
        lineHeight: 15.73,
        color: '#222',
    },
    label: {
        fontFamily: 'Inter',
        fontWeight: 500,
        fontSize: 13,
        lineHeight: 15.73,
        color: '#222',
    },
};

export { FONTS };
