const ANIMATION_VALUES = {
    INITIAL_PROGRESS_VALUE: 0,
    FINAL_PROGRESS_VALUE: 1,
    TEXT_INITIAL_Y_COORDINATES: -200,
    TEXT_FINAL_Y_COORDINATES: 0,
    ICON_INITIAL_X_COORDINATES: -100,
    ICON_FINAL_X_COORDINATES: 0,
};

const STEP_TO_ACTIVE_SCREEN = 1;

export { ANIMATION_VALUES, STEP_TO_ACTIVE_SCREEN };
