const TALENT_ONBOARDING_PROFILE_CONSTANTS = {
    MIN_PROFILE_LENGTH: 2,
    MAX_PROFILE_LENGTH: 50,
    PROFILE_REGEXP: /^[\s'.A-Za-z]+$/,

    MIN_SALARY: 1,
    MAX_SALARY: 9999,

    MIN_EXPERIENCE_YEARS: 0,
    MAX_EXPERIENCE_YEARS: 5,

    MIN_EMPLOYMENT_TYPES: 1,

    MIN_DESCRIPTION_LENGTH: 10,
    MAX_DESCRIPTION_LENGTH: 250,
    DESCRIPTION_REGEXP: /^[\d\s"',.A-Za-z]+$/,
};

export { TALENT_ONBOARDING_PROFILE_CONSTANTS };
