name: Continuous Integration

on:
    pull_request:
        branches:
            - development
            - production

concurrency:
    group: ci-${{ github.ref }}
    cancel-in-progress: true

jobs:
    ci:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Source Code
              uses: actions/checkout@v3

            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x

            - name: Install Dependencies
              with:
                  npm-version: 8.x.x
              run: |
                  npm install

            - name: Code Linting
              run: |
                  npm run lint
